In [1]:
import pandas as pd
import numpy as np

## Loading and Reading Data

### Data loading and data formats

If you recall, in the first module, you learned the amount of data residing in various sources is vast and, also, constantly getting generated in our devices (including cloud). All of this data needs to be accessed at some point in time and it all starts with data ingestion!

Data ingestion is a process of reading and loading data into Python from various underlying data sources, such that data can then be processed and transformed as per the requirements of the application. Each kind of data source has their own protocol for transferring data and as an analyst you must understand the difference among them. Most of the time, the loaded data are available to us in the following formats:

- Text data (CSV, JSON, Excel, etc)
- Web data (HTML, XML)
- Databases (SQL and NoSQL Data)
- Binary data formats

In this module, we will go into the details of some of the functions related to data ingestion for the CSV, JSON, HTML, and SQL data formats. We will also provide references to detailed documentation for other data types and different variations of data ingestion possible.

### Reading and writing text data

Due to its simple syntax for interacting with files, intuitive data structures, and convenient features like tuple packing and unpacking, Python has become the go-to language for text data. Pandas have several functions for reading tabular data as a DataFrame object. 

Here are some of these functions:

| Function | Description   |
|------|------|
|   read_csv()  | Load delimited data from a file, URL, or file-like object. “,” – comma is the default delimiter|
|  read_table()  | Load delimited data from a file, URL, or file-like object. “\t” – tab is the default delimiter|
|   read_fwf()  | Read data in fixed width column format, that is there is no delimiter|

In this course, you will most commonly use the read_csv() and read_table() functions. For the full list of I/O functions available in Pandas you can refer to following link:<br>
https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html

### CSV functions 

A CSV (comma separated values) file is a type of plain text file. These csv files, the 'comma separated' files, are how columns and fields are identified in the value.
    
For example:
    
ColumnA_header, ColumnB_header, ColumC_header
ColumnA_value1, ColumnB_value2, ColumnC_value2
ColumnA_value2, ColumB_value2, ColumnC_value3

Let us explore the details of the discussed CSV functions used to convert the text data into a DataFrame. 
If you think about it, you may realise that these functions should have parameters related to the following functionalities and features related to DataFrame:


Let us explore the details of the discussed CSV functions used to convert the text data into a DataFrame. 

If you think about it, you may realise that these functions should have parameters related to the following functionalities and features related to DataFrame:

#### Indexing options 

Column names need to be read from the file, or the user, or not at all, and use the default column name conventions

Row labels need to be considered as a particular data column in the file as the row label, or use the default row indexing

For example: 
Naming individual columns and rows with unique names so that they are identified when called

#### Type inferences and data conversion options

Value conversion options as defined by the user.

Custom input data to deal with missing value markers.

For example:
Converting a particular value in a cell of the DataFrame; this also included replacing with a new value or inputting the default NaN for missing values.

#### DateTime parsing-related options

Capability to combine the date and time information spread across multiple columns in the input data and merging the combined data into a single column in the result.

For example:
Combining month, day, and year to produce a full date.

#### Iteration-related options

Iterate over smaller chunks of data in the case of large files.

For example:
Repeating the same customer ID for a particular name anywhere in the file.

#### Data Issue-related options

Options to deal with data nuances

For example: 
Skipping rows or a footer, comments, or others such as numeric data with commas used in the representation


#### Evaluating CSV functions

Now, let’s evaluate these functions and various options. There are different sample CSV files that are stored in the module directory (if you don’t have one created, create one for storing all the files you just downloaded under datasets in the start of this topic), and we will be using these files to perform the read operations and numerous variations of it.

You can see that there are comma-separated values in the file. We’ll show you how to use the function read_csv() and also check the various parameters available for this function.

### Basic Read Operation of the csv File

Make sure you have the file named sample_data.txt downloaded on your machine. Next, enter the code snippet that demonstrates the use of the read_csv function:

Following code snippet demonstrates the use of the __read_csv__ function: 

In [2]:
#Reading the sample data from the dataset folder. Filename is stored in the variable filename
filename = "./dataset/sample_data.txt"
df= pd.read_csv(filename)
df

a   b   c     d  comments
0   1   2   3     4  comment1
1   5   6   7     8  comment2
2   9  10  11  Adam  comment3
3  12  13  14    15  comment4
4  I1  16  17    18  comment5

Based on these results, the following can be observed:

- The first row of the file has been considered as the name of the columns by default.
- The default row labels (row indexes) have been considered (look at the values 0,1,2,3,4).
- Parsing of the values has happened automatically (i.e., we didn't have to specify the ’,’ as the delimiter explicitly).


### Specifying the Column Names

Tables in excel generally come with the header rows that contain the information that either identifies the content of a particular column or the number of the column. 

There are scenarios where you may have to explicitly specify whether the header row in a table exists or not. The parameter header of the function controls this behaviour. So if you pass the value header=None, it will not consider the first row as the header and instead as a data record. In this case, column names for the DataFrame will automatically generate.
 
Make sure you have the file named sample_data_noheader.txt downloaded on your machine.

Next, we will now read this file and instruct the read_csv function to consider the first row as the data record.

In [3]:
filename = "./dataset/sample_data_noheader.txt"
df= pd.read_csv(filename, header=None)
df

0   1   2     3         4
0   1   2   3     4  comment1
1   5   6   7     8  comment2
2   9  10  11  Adam  comment3
3  12  13  14    15  comment4
4  I1  16  17    18  comment5

In this particular scenario, there could be a requirement to explicitly provide the column names instead of relying on the auto indexing for column names.

In that case we use the parameter __names__ and pass the list of column names to the read_csv() function. When we pass the __names=[list of column names]__, we dont have to pass the parameter __header=None__ to the read_csv function.

See below code snippet for the demonstration:

In [4]:
names=['a','b','c','d','comments']
df=pd.read_csv(filename, names=names)
df

a   b   c     d  comments
0   1   2   3     4  comment1
1   5   6   7     8  comment2
2   9  10  11  Adam  comment3
3  12  13  14    15  comment4
4  I1  16  17    18  comment5

### Specifying the Row Labels / Row Index from a Column in the data file

Let us say you now have your columns labeled with individual header rows such as mango, apple, and grape. You might then decide to explicitly name that row as fruits. Python comes handy in such scenarios where you would like to explicitly specify the row labels (row indexes) instead of using the default indexes.

In the current example, assume that we want the comment section to be the row label of the DataFrame. This can be achieved by using the __index_col__ parameter of the function, and specifying the name of the column to be used as the row label.

See the code snippet below for the demonstration

In [5]:
df=pd.read_csv(filename, names=names, index_col='comments')
df

a   b   c     d
comments                  
comment1   1   2   3     4
comment2   5   6   7     8
comment3   9  10  11  Adam
comment4  12  13  14    15
comment5  I1  16  17    18

In [6]:
df.loc['comment1']

a    1
b    2
c    3
d    4
Name: comment1, dtype: object

Based on these results, the following can be observed:

the comment column from the input data file has now been used to specify the row labels of the DataFrame

you can access the first row of the DataFrame using the key __"comment1"__

### Hierarchical Indexing

Let us say you want to include a hierarchical indexing functionality. Instead of one column (from the previous example, such as Fruits) considered as an index, you have a hierarchy of columns considered as indexes (such as fruit varieties Tropical and Exotic). These indexes can have the same values such as mango, apple, and grape; but now they are specific to the index names and can either be a tropical mango, apple, and grape or an exoctic mango, apple, and grape.

Make sure you have the file named sample_data_hierarchy.txt downloaded on your machine.

In this particular case first two columns together can be considered as the row index. For such a scenario we would have to pass the list of columns to be considered as hierarchical index to the __read_csv__ function, using the __index_col__ parameter.

See the code snippet below for demonstration:


In [7]:
filename = "./dataset/sample_data_hierarchy.txt"
names=['I1','I2','col1','col2','col3','col4','comments']
df= pd.read_csv(filename, names=names, index_col=['I1','I2'])
df

col1  col2  col3  col4  comments
I1 I2                                 
A  1     0     1     2     3  comment1
   2     1     2     3     4  comment2
   3     5     6     7     8  comment3
   4     9    10    11  Adam  comment4
B  1    12    13    14    15  comment5
   2    I1    16    17    18  comment6
   3    I2    19    20    21  comment7

In [8]:
df.loc['A',1]

col1               0
col2               1
col3               2
col4               3
comments    comment1
Name: (A, 1), dtype: object

Based on these results, the following can be observed:
 
- we have read the data file, specified the column names bypassing the list of column names to the parameter __names__
- we have also specified the hierarchical indexing to be used by passing the list of column names to be considered as indexes to the parameter __index_col__
- we are accessing the first row of the DataFrame using the hierarchical index 'A',1.

### Specifying the Seperator / Delimiter explicitly

You were introduced to csv as comma separated values files, where the default delimiter was a comma (,). But, what if that default delimiter would not work? In such cases, you may have to specify the separator / delimiter explicitly when reading the data from the file. 

For example:

If white space is used as the separator instead of the default value comma ',', you might need to write a separate code to call out the delimiter explicitly. 

In this case, you can specify the separator to be used by using the parameter __sep__ and passing the value of the separator. 

Consider the file named sample_data_noheader_space.txt (make sure you have this downloaded on your machine) where white space is used as the separator / delimiter. To read this file correctly in the DataFrame, we will use the parameter __sep__

The code snippet demonstrates when we have not used the sep parameter, and all the values in the first column of the DataFrame have been read.


In [9]:
filename = "./dataset/sample_data_noheader_space.txt"
names=['a','b','c','d','comments']
df= pd.read_csv(filename, header=None, names=names)
df

a   b   c   d  comments
0       1 2 3 4 comment1 NaN NaN NaN       NaN
1       5 6 7 8 comment2 NaN NaN NaN       NaN
2  9 10 11 Adam comment3 NaN NaN NaN       NaN
3   12 13 14 15 comment4 NaN NaN NaN       NaN
4   I1 16 17 18 comment5 NaN NaN NaN       NaN

As you can see when we have not used the parameter __sep__ all the values have been read in the first column of the DataFrame. Let's now specify the __sep__ parameter and read the data correctly

In [10]:
df= pd.read_csv(filename, header=None, names=names, sep=" ")
df

a   b   c     d  comments
0   1   2   3     4  comment1
1   5   6   7     8  comment2
2   9  10  11  Adam  comment3
3  12  13  14    15  comment4
4  I1  16  17    18  comment5

As you can see above the data has now been read correctly into the DataFrame.

### Skipping the specified Rows while reading data from a file

There could be scenario's where specific rows need to be ignored while reading the data from a file.

For example: 

- when there are fixed line comments at the top, or
- when you have comments at the fixed line numbers in the file, or
- say the footer line in the text file.

In this case, we will use the __skiprows__ parameter of the __read_csv__ function. We have to pass the index number of the row to this parameter. Whilst, in case we want to ignore multiple rows, we must be able to pass the list of row indexes to this parameter.

In this particular case we will ignore the 1st, 2nd, 3rd and 6th row by passing the indexes 0,1,2 and 5 respectively.
See the code snippet below for the demonstration:


In [11]:
filename = "./dataset/sample_data_comments.txt"
names=['a','b','c','d','comments']
df= pd.read_csv(filename, header=None, names=names)
df

a               b    c     d  \
0          #This is the Row 1 to be ignored             NaN  NaN   NaN   
1          #This is the Row 2 to be ignored             NaN  NaN   NaN   
2  #This is the Comment Row 3 to be ignored             NaN  NaN   NaN   
3                                         a               b    c     d   
4                                         1               2    3     4   
5         #This is the 6th row in this file   to be ignored  NaN   NaN   
6                                         5               6    7     8   
7                                         9              10   11  Adam   
8                                        12              13   14    15   
9                                        I1              16   17    18   

   comments  
0       NaN  
1       NaN  
2       NaN  
3  comments  
4  comment1  
5       NaN  
6  comment2  
7  comment3  
8  comment4  
9  comment5

As you can see above if we dont specify the __skiprows__ parameter, then the DataFrame has not been parsed properly. The first 3 comment rows have been read and depending on whethere there is , in the comment the value has been parsed into either the first column or more.

We will now perform this read operation by correctly specifying the __skiprows__ parameter.

In [12]:
df= pd.read_csv(filename, header=None, names=names, skiprows=[0,1,2,5])
df

a   b   c     d  comments
0   a   b   c     d  comments
1   1   2   3     4  comment1
2   5   6   7     8  comment2
3   9  10  11  Adam  comment3
4  12  13  14    15  comment4
5  I1  16  17    18  comment5

As you can see now, the DataFrame has been correctly populated.

### Skipping the Footer while reading a Text File

Similarly, a text file may contain elements such as a footer that you may want to ignore as a row while reading the file because it might be irrelevant to the analysis you are conducting. In such cases, you will use the parameter __skipfooter__ and pass an integer value equal to the number of lines to ignore while reading the file. 

Make sure you have the file named sample_data_footer.txt downloaded on your machine. 

In [13]:
filename = "./dataset/sample_data_footer.txt"
names=['a','b','c','d','comments']
df= pd.read_csv(filename, header=None, names=names, skipfooter=1)
df

<ipython-input-13-9d76c2098363>:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  df= pd.read_csv(filename, header=None, names=names, skipfooter=1)


a   b   c     d  comments
0   a   b   c     d  comments
1   1   2   3     4  comment1
2   5   6   7     8  comment2
3   9  10  11  Adam  comment3
4  12  13  14    15  comment4
5  I1  16  17    18  comment5

### Handling Missing Data while reading data from a file

In the examples shown, you may have observed that when data is missing, the default behaviour is to replace the missing value with NaN. Handling missing values is an integral part of the file-parsing process, with some subtle nuances:

Explicitly specifying the input values to be considered as missing values while reading the file.
These are scenarios when a specific naming convention may denote the missing values in the input file. 

For example:
- Some data might have ‘Missing’ to specify the missing data values
- Some might even have ‘99999999’ to specify missing reading in case of numeric values
- Some might even have a combination of both ‘Missing’ and ‘99999999’ for different data columns in the file

If you consider the next file example, some rows have missing values. Look for no value between two commas. Also, there are some rows where it is explicitly noted as ‘Missing’ (the notation could be anything; eg, NA instead of missing).
 
Make sure you have the file named sample_data_missingvalues.txt downloaded on your machine. 
The code snippet demonstrates reading this file first without explicitly specifying that ‘Missing’ be considered as a missing value.

In [14]:
#Default read operation, without specifying the explicity missing value notations
filename = "./dataset/sample_data_missingvalues.txt"
names=['a','b','c','d','comments','Value']
df= pd.read_csv(filename, header=None, names=names)
df

a        b        c     d        comments   Value
0   1        2      NaN     4        comment1       1
1   5      NaN        7     8        comment2       2
2   9      foo      foo  Adam             NaN       3
3  12      foo       14    15        comment4  999999
4  I1       16       17    18        comment5  999999
5  I2  Missing       18    19         Missing       4
6  I3  Missing  Missing    20  comments added      -1

Now, let’s read the same file by specifying the missing values using the __na_values__ parameter.

In [15]:
#Read operation by specifying a missing value notation
df= pd.read_csv(filename, header=None, names=names, na_values="Missing")
df

a    b    c     d        comments   Value
0   1    2  NaN     4        comment1       1
1   5  NaN    7     8        comment2       2
2   9  foo  foo  Adam             NaN       3
3  12  foo   14    15        comment4  999999
4  I1   16   17    18        comment5  999999
5  I2  NaN   18    19             NaN       4
6  I3  NaN  NaN    20  comments added      -1

Based on these results, the following can be observed:

- Row index 5, and columns b and comments – the string ‘Missing’ has been inferred as missing value NaN.
- Row index 6 and column b and c – the string ‘Missing’ has been inferred as missing value NaN.

We can extend this scenario and set the following requirements:

- Columns a,b,c,d and comments – string ‘Missing’ has to be treated as missing values.
- Column ‘Value’ – value 999999 has to be treated as a missing value.

This can be achieved by passing the dictionary object to na_values where:

- key – the name of columns.
- value – the list of values to be considered as the missing value for those columns.

The code snippets demonstrate how:

- The values 'foo' and 'Missing' will be considered as missing values for columns a,b,c,d and comments.
- The values -1 and 999999 will be considered as the missing value for the column Value.

In [16]:
dict_missing = {
    'a':['foo','Missing'],
    'b':['foo','Missing'],
    'c':['foo','Missing'],
    'd':['foo','Missing'],
    'comments':['foo','Missing'],
    'Value':[999999, -1]
}


In [17]:
df= pd.read_csv(filename, header=None, names=names, na_values=dict_missing)
df

a     b     c     d        comments  Value
0   1   2.0   NaN     4        comment1    1.0
1   5   NaN   7.0     8        comment2    2.0
2   9   NaN   NaN  Adam             NaN    3.0
3  12   NaN  14.0    15        comment4    NaN
4  I1  16.0  17.0    18        comment5    NaN
5  I2   NaN  18.0    19             NaN    4.0
6  I3   NaN   NaN    20  comments added    NaN

### Reading Text File in Pieces / Small Chunks

When processing huge files, you may want to:

- only read a small portion of the file to figure out the right set of arguments to be used
- read the file in smaller chunks and iterate over it sequentially.

There are two parameters we can use in this scenario:
- nrows –  specifies the number of rows to be read.
- chunksize – specifies the number of rows to be read as one chunk. 

In this particular case, the read_csv will return a File Iterator instead of a DataFrame. We can use this iterator to create the resulting DataFrame or perform quantitative calculations.

Make sure you have the file named sample_data_large.csv downloaded on your machine. 

The code snippet demonstrates using __nrows__.

In [18]:
#Reading the smaller sample of the file by specifying the nrow parameter
filename = "./dataset/sample_data_large.csv"
df= pd.read_csv(filename, nrows=10)
df

Row Label  Column 1  Column 2  Column 3  Column 4  Values
0        R1        78      1128      9336      6111   21069
1        R2        77      2881      8379       801  822749
2        R3        62      2966      6989       241  869213
3        R4        91      8032      4315      6801  198173
4        R5         0      6983      7195      7615  464909
5        R6        17      2322      1139      2828  438359
6        R7        95      7205      4518      3437   54932
7        R8        32      6033       392      1725  785029
8        R9         1      6710      2368      1858   41489
9       R10        25      8678      1519      3866  481310

As you can see only 10 top rows have been read in this particular case.

Let's now explore the use of __chunksize__ and __File Iterator__.

In [19]:
#Reading the big file in one go to check whether it has reached the limit or not,
#and verify the row count
filename = "./dataset/sample_data_large.csv"
df= pd.read_csv(filename)
df

Row Label  Column 1  Column 2  Column 3  Column 4  Values
0              R1        78      1128      9336      6111   21069
1              R2        77      2881      8379       801  822749
2              R3        62      2966      6989       241  869213
3              R4        91      8032      4315      6801  198173
4              R5         0      6983      7195      7615  464909
...           ...       ...       ...       ...       ...     ...
1048570  R1048571         9      5727      3920      3927  853689
1048571  R1048572        80      6758      9772      9576  519973
1048572  R1048573        95      7793      3635      5936  220089
1048573  R1048574         9      1984      5527      8149  823118
1048574  R1048575         3      5225      8501       321  396382

[1048575 rows x 6 columns]

In [20]:
df.describe()

Column 1      Column 2      Column 3      Column 4        Values
count  1.048575e+06  1.048575e+06  1.048575e+06  1.048575e+06  1.048575e+06
mean   5.001918e+01  5.052930e+03  5.052788e+03  5.050653e+03  5.002445e+05
std    2.914091e+01  2.858973e+03  2.856928e+03  2.857718e+03  2.886466e+05
min    0.000000e+00  1.000000e+02  1.000000e+02  1.000000e+02  1.000000e+00
25%    2.500000e+01  2.576000e+03  2.578000e+03  2.575000e+03  2.503700e+05
50%    5.000000e+01  5.054000e+03  5.054000e+03  5.054000e+03  5.004660e+05
75%    7.500000e+01  7.531000e+03  7.525000e+03  7.527000e+03  7.498935e+05
max    1.000000e+02  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+06

Let's look at the memory footprint of the DataFrame that we have just read.

In [21]:
print("The memory footprint of the DataFrame is: %f MB"%(df.memory_usage().sum()/(1024 * 1024)))


The memory footprint of the DataFrame is: 48.000076 MB


Assume the requirement is to calculate the sum of the values in the ‘Values’ column. This can be achieved without creating a DataFrame by using the File Iterator and performing the summation for the specific columns.

This would have a significantly smaller memory footprint and would result in code that performs better. We can access the File Iterator by:

- using the chunksize parameter and specifying the integer value
- specifying the iterator parameter and passing the boolean value True.

If you calculate this sum using DataFrame as well as the iterator, conducting memory profiling for both operations, you can expect that: 

- summation using DataFrame will require a larger memory footprint but less execution time
- summation using Iterator will have lesser memory footprint (but more execution time because of multiple data movements to memory for calculation.

The code snippet demonstrates using Python's memory and execution time profile to check these values. 

If you don't have the module install it using the following command in your terminal/shell:

conda install -c anaconda memory_profiler

In [22]:
import memory_profiler, time

In [23]:
## Memory and Time Profiling with the DataFrame Operation
if __name__ == '__main__':
    m1 = memory_profiler.memory_usage()
    t1 = time.process_time()
#Print the sum     
    filename = "./dataset/sample_data_large.csv"
    df= pd.read_csv(filename)
    total = df['Values'].sum()
    print("Total Values: %d "%total)

    t2 = time.process_time()
    m2 = memory_profiler.memory_usage()
    time_diff = t2 - t1
    mem_diff = m2[0] - m1[0]
    print(f"It took {time_diff} Secs and {mem_diff} Mb to execute this method")

Total Values: 524543837226 
It took 0.7295690000000001 Secs and 76.390625 Mb to execute this method


In [24]:
## Memory and Time Profiling with the File Iterator Operation
if __name__ == '__main__':
    m1 = memory_profiler.memory_usage()
    t1 = time.process_time()
#Print the sum     
    filename = "./dataset/sample_data_large.csv"
    iter = pd.read_csv(filename,chunksize=1000)
    total_value = 0
    for record in iter:
        total_value+=record['Values'].sum()
    print(total_value)

    t2 = time.process_time()
    m2 = memory_profiler.memory_usage()
    time_diff = t2 - t1
    mem_diff = m2[0] - m1[0]
    print(f"It took {time_diff} Secs and {mem_diff} Mb to execute this method")

524543837226
It took 3.707782 Secs and -49.2890625 Mb to execute this method


The memory footprint is significantly less when using File Iterator.


__Note:__ We have used read_csv() in our demonstration, but we can also use the read_table() function. The main difference between the two functions is the default value of delimiter / separator considered by the two functions. 
read_csv function considers a comma ',' as the default delimiter. 
read_table function considers tab '\t' as the default delimiter.

For detailed information on the numerous parameters that can be specified for the read_csv() function, refer to the following link: 

Go to:  Pandas 1.1.3 documentation [2]
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html


## Reading Data in JSON Format

JSON (Javascript Object Notation) is now a widely used data format in web applications. Almost all of the current APIs transfer data using JSON format. It is a flexible data format in comparison to the tabular data formats like CSVs.


### Basic Read Operation of the JSON File

Pandas has the function __read_json()__ to read JSON formatted data. In its simplest form, you need to specify the location of the JSON data file, and it will be read into a DataFrame.

Consider the below sample file having a JSON data format. Make sure you have the file sample_data.json downloaded on your machine.

You may realise that this data representation is very similar to Python's dictionary notation. In this particular case, the default behaviour would be to consider:

- the subkeys (0,1,2, etc) as the row labels.
- the top-level keys (Product and Price) as the column labels.

The code snippet demonstrates this behaviour:


In [25]:
filename = "./dataset/sample_data.json"
df= pd.read_json(filename)
df

Product  Price
0         Laptop   1500
1        Desktop   1000
2         Tablet    700
3         iPhone   1800
4  Android Phone   1200

Depending on how the data is formatted in JSON, it would have an impact on how the DataFrame is created. 

By default:

- top-level key is considered the Column Name (0,1,2, etc)
- key at nested level 1 is considered the Row Label (Price, Product).

Consider the following JSON formatted file. Make sure you have the file sample_data_index.json downloaded on your machine:

As highlighted, this time ‘0,1,2’ will be the column labels and ‘Price and Product’ will become the row labels.
 
The code snippet demonstrates this.

In [26]:
filename = "./dataset/sample_data_index.json"
df= pd.read_json(filename)
df

0        1       2       3        4
Product  Laptop  Desktop  Tablet  iPhone  Android
Price      1500     1000     700    1800     1200

Now you may need to control the behaviour in terms of how the DataFrame is created. Say for e.g., using the same format of the input JSON data you want that Price and Product be the Column Names, and 0,1,2..etc., be the row labels.

### Data Orientation in JSON files

Data orientation behaviour can be controlled using the parameter orient. This parameter has following possible values:

- 'split' – dict like {index -> [index], columns -> [columns], data -> [values]}
- 'records' – list like [{column -> value}, ... , {column -> value}]
- 'index' – dict like {index -> {column -> value}}
- 'columns' – dict like {column -> {index -> value}}
- 'values' – only the values array

As you can infer from the examples, the default expected orientation is Columns Orientation.

#### INDEX formatted JSON Data

In the example, the JSON data is formatted in the index format (ie {row#:{Column: Value}} format) so if we specify the orient=index, we will get the DataFrame in the desired format.
 
Consider the following JSON formatted file we had used previously.

In [27]:
df= pd.read_json(filename, orient='index')
df

Product  Price
0   Laptop   1500
1  Desktop   1000
2   Tablet    700
3   iPhone   1800
4  Android   1200

#### SPLIT formatted JSON Data

Consider the following JSON formatted file - JSON data is formatted as below i.e. {index:{values}, column1:{values}, columns2:{values}. Make sure you have the file sample_data_split.json downloaded on your machine:

You will use the __orient=split__ specification to create the DataFrame properly.

The code snippet demonstrates.

In [28]:
filename = "./dataset/sample_data_split.json"
df= pd.read_json(filename, orient='split')
df

Product  Price
0   Laptop   1500
1  Desktop   1000
2   Tablet    700
3   iPhone   1800
4  Android   1200

Numerous variations and customisations may be needed while using the read_json function, depending on the structure of the data in the JSON formatted file. In this section, we have only covered the basics, and for detailed reference of input / output related JSON, please refer to the following link: 

https://pandas.pydata.org/pandas-docs/version/0.23.4/io.html#json

## Reading HTML and XML Data: Web Scrapping

At many times, when websites don't provide downloadable, machine-readable data formats like JSON, XML, and so on, the data might be represented as HTML formatted tables.
 
If this happens, you may need a way to read the HTML tables directly. Pandas have a top-level __read_html()__ function that can accept an HTML string / file / URL and will parse the HTML table into the list of the Pandas DataFrame.
 
### Basic read of HTML files / URLs
 
The __read_html()__ function can be used to read HTML formatted data. Let's understand this behaviour using an example list from the Federal Deposit Insurance Corporation (FDIC) in the USA. The FDIC is often appointed as a receiver for failed banks and the list we’re using includes information on banks that have failed since 1 October 2000.  
    

We will extract the data from the following URL:<br>
__'http://www.fdic.gov/bank/individual/failed/banklist.html'__



In [29]:
url='http://www.fdic.gov/bank/individual/failed/banklist.html'
dfs = pd.read_html(url)
dfs

[                             Bank Name               City  ST   CERT  \
 0                    Almena State Bank             Almena  KS  15426   
 1           First City Bank of Florida  Fort Walton Beach  FL  16748   
 2                 The First State Bank      Barboursville  WV  14361   
 3                   Ericson State Bank            Ericson  NE  18265   
 4     City National Bank of New Jersey             Newark  NJ  21111   
 ..                                 ...                ...  ..    ...   
 558                 Superior Bank, FSB           Hinsdale  IL  32646   
 559                Malta National Bank              Malta  OH   6629   
 560    First Alliance Bank & Trust Co.         Manchester  NH  34264   
 561  National State Bank of Metropolis         Metropolis  IL   3815   
 562                   Bank of Honolulu           Honolulu  HI  21029   
 
                    Acquiring Institution       Closing Date  
 0                            Equity Bank   October 23, 202

Based on these results, the following can be observed:
 
- this call has extracted all the 561 data records from the HTML table on the web pages
- the output data is in the List Format, and not the DataFrame. This way, if there are multiple HTML tables on the webpage, we would get the list of various data frames.


Next, let's check the __type__ of variable dfs – this should be a list. If we access the __first element__ of the list, this should return a DataFrame.

In [30]:
type(dfs)

list

In [31]:
df=dfs[0]
df.head()

Bank Name               City  ST   CERT  \
0                 Almena State Bank             Almena  KS  15426   
1        First City Bank of Florida  Fort Walton Beach  FL  16748   
2              The First State Bank      Barboursville  WV  14361   
3                Ericson State Bank            Ericson  NE  18265   
4  City National Bank of New Jersey             Newark  NJ  21111   

        Acquiring Institution       Closing Date  
0                 Equity Bank   October 23, 2020  
1   United Fidelity Bank, fsb   October 16, 2020  
2              MVB Bank, Inc.      April 3, 2020  
3  Farmers and Merchants Bank  February 14, 2020  
4             Industrial Bank   November 1, 2019

Next, try inputting the code shown below and check what could be the possible return? 

In [32]:
df.describe(include="all")

Bank Name     City   ST          CERT  \
count                    563      563  563    563.000000   
unique                   546      433   44           NaN   
top     The First State Bank  Chicago   GA           NaN   
freq                       3       20   93           NaN   
mean                     NaN      NaN  NaN  31630.271758   
std                      NaN      NaN  NaN  16443.670177   
min                      NaN      NaN  NaN     91.000000   
25%                      NaN      NaN  NaN  20096.500000   
50%                      NaN      NaN  NaN  32165.000000   
75%                      NaN      NaN  NaN  35364.000000   
max                      NaN      NaN  NaN  58701.000000   

       Acquiring Institution      Closing Date  
count                    563               563  
unique                   297               258  
top              No Acquirer  October 30, 2009  
freq                      31                 9  
mean                     NaN               NaN  
std                      NaN               NaN  
min                      NaN               NaN  
25%                      NaN               NaN  
50%                      NaN               NaN  
75%                      NaN               NaN  
max                      NaN               NaN

We have seen in read_csv and read_json functions that there are numerous configuration parameters that control how the data is read, and the same is true with the read_html() function as well.

We will explore some of the standard specifications next:
 
- specifying the row index
- specifying the header value
- specifying the number of rows to be skipped


### Specifying the Row Label / Row Index

This can be done by using the __index_col__ parameter, and specifying the column name or index of the columns to be used as the Row Label. In our example we will use first column as the Row Labels, and hence we will pass the value __0__ to this parameter

See the code snippet below for demonstration:

In [33]:
url='http://www.fdic.gov/bank/individual/failed/banklist.html'
dfs = pd.read_html(url,index_col=0)
df=dfs[0] #first element of list is a dataframe
df

City  ST   CERT  \
Bank Name                                                         
Almena State Bank                             Almena  KS  15426   
First City Bank of Florida         Fort Walton Beach  FL  16748   
The First State Bank                   Barboursville  WV  14361   
Ericson State Bank                           Ericson  NE  18265   
City National Bank of New Jersey              Newark  NJ  21111   
...                                              ...  ..    ...   
Superior Bank, FSB                          Hinsdale  IL  32646   
Malta National Bank                            Malta  OH   6629   
First Alliance Bank & Trust Co.           Manchester  NH  34264   
National State Bank of Metropolis         Metropolis  IL   3815   
Bank of Honolulu                            Honolulu  HI  21029   

                                                 Acquiring Institution  \
Bank Name                                                                
Almena State Bank                                          Equity Bank   
First City Bank of Florida                   United Fidelity Bank, fsb   
The First State Bank                                    MVB Bank, Inc.   
Ericson State Bank                          Farmers and Merchants Bank   
City National Bank of New Jersey                       Industrial Bank   
...                                                                ...   
Superior Bank, FSB                               Superior Federal, FSB   
Malta National Bank                                  North Valley Bank   
First Alliance Bank & Trust Co.    Southern New Hampshire Bank & Trust   
National State Bank of Metropolis              Banterra Bank of Marion   
Bank of Honolulu                                    Bank of the Orient   

                                        Closing Date  
Bank Name                                             
Almena State Bank                   October 23, 2020  
First City Bank of Florida          October 16, 2020  
The First State Bank                   April 3, 2020  
Ericson State Bank                 February 14, 2020  
City National Bank of New Jersey    November 1, 2019  
...                                              ...  
Superior Bank, FSB                     July 27, 2001  
Malta National Bank                      May 3, 2001  
First Alliance Bank & Trust Co.     February 2, 2001  
National State Bank of Metropolis  December 14, 2000  
Bank of Honolulu                    October 13, 2000  

[563 rows x 5 columns]

In [34]:
df.loc['The First State Bank']

City  ST   CERT Acquiring Institution  \
Bank Name                                                              
The First State Bank  Barboursville  WV  14361        MVB Bank, Inc.   
The First State Bank    Stockbridge  GA  19252   Hamilton State Bank   
The First State Bank        Camargo  OK   2303                Bank 7   

                          Closing Date  
Bank Name                               
The First State Bank     April 3, 2020  
The First State Bank  January 20, 2012  
The First State Bank  January 28, 2011

In [35]:
url='http://www.fdic.gov/bank/individual/failed/banklist.html'
dfs = pd.read_html(url,skiprows=10)
df=dfs[0] #first element of list is a dataframe
df

The Farmers and Merchants State Bank of Argonia             Argonia  \
0                                  Fayette County Bank          Saint Elmo   
1    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
2                                       First NBC Bank         New Orleans   
3                                        Proficio Bank  Cottonwood Heights   
4                        Seaway Bank and Trust Company             Chicago   
..                                                 ...                 ...   
548                                 Superior Bank, FSB            Hinsdale   
549                                Malta National Bank               Malta   
550                    First Alliance Bank & Trust Co.          Manchester   
551                  National State Bank of Metropolis          Metropolis   
552                                   Bank of Honolulu            Honolulu   

     KS  17719                          Conway Bank   October 13, 2017  
0    IL   1802            United Fidelity Bank, fsb       May 26, 2017  
1    WI  30003  First-Citizens Bank & Trust Company        May 5, 2017  
2    LA  58302                         Whitney Bank     April 28, 2017  
3    UT  35495                    Cache Valley Bank      March 3, 2017  
4    IL  19328                  State Bank of Texas   January 27, 2017  
..   ..    ...                                  ...                ...  
548  IL  32646                Superior Federal, FSB      July 27, 2001  
549  OH   6629                    North Valley Bank        May 3, 2001  
550  NH  34264  Southern New Hampshire Bank & Trust   February 2, 2001  
551  IL   3815              Banterra Bank of Marion  December 14, 2000  
552  HI  21029                   Bank of the Orient   October 13, 2000  

[553 rows x 6 columns]

The code snippet shows how we can access the records using the row label (bank names).

In [36]:
dfs1=pd.read_html(url,attrs={'id':'table'})
dfs2=pd.read_html(url,attrs={'class':'tablesorter'})
print(np.array_equal(dfs1[0], dfs2[0]))

True


In [37]:
dfs1[0].head()

Bank Name               City  ST   CERT  \
0                 Almena State Bank             Almena  KS  15426   
1        First City Bank of Florida  Fort Walton Beach  FL  16748   
2              The First State Bank      Barboursville  WV  14361   
3                Ericson State Bank            Ericson  NE  18265   
4  City National Bank of New Jersey             Newark  NJ  21111   

        Acquiring Institution       Closing Date  
0                 Equity Bank   October 23, 2020  
1   United Fidelity Bank, fsb   October 16, 2020  
2              MVB Bank, Inc.      April 3, 2020  
3  Farmers and Merchants Bank  February 14, 2020  
4             Industrial Bank   November 1, 2019

In [38]:
dfs2[0].head()

Bank Name               City  ST   CERT  \
0                 Almena State Bank             Almena  KS  15426   
1        First City Bank of Florida  Fort Walton Beach  FL  16748   
2              The First State Bank      Barboursville  WV  14361   
3                Ericson State Bank            Ericson  NE  18265   
4  City National Bank of New Jersey             Newark  NJ  21111   

        Acquiring Institution       Closing Date  
0                 Equity Bank   October 23, 2020  
1   United Fidelity Bank, fsb   October 16, 2020  
2              MVB Bank, Inc.      April 3, 2020  
3  Farmers and Merchants Bank  February 14, 2020  
4             Industrial Bank   November 1, 2019

### Specifying Null Values 

Using the parameter na_values, we can pass the list of data values considered as null.

The code snippet shows passing the value  __'No Acquirer'__ as the null value to the read_html function, which will then replace these values with NaN when stored in the DataFrame:

First specify the null values:


In [39]:
#Specifying Null Values
dfs=pd.read_html(url,attrs={'id':'table'}, na_values=["No Acquirer"], index_col=0)
df=dfs[0]

In [40]:
df.loc[['Dollar Savings Bank', 'Bank of Alamo']]

City  ST   CERT Acquiring Institution  \
Bank Name                                                      
Dollar Savings Bank  Newark  NJ  31330                   NaN   
Bank of Alamo         Alamo  TN   9961                   NaN   

                          Closing Date  
Bank Name                               
Dollar Savings Bank  February 14, 2004  
Bank of Alamo         November 8, 2002

Note that Web Scrapping is a very wide topic, and you can spend days and months just focusing on Web Scrapping. In this section we have just touched on the very basics of the scraping HTML Data.

Python ecosystem provides variety of libraries that can be used for Web Scrapping. For e.g.
1.  __lxml__ -> provides both HTML and XML Scrapping and Data Parsing capabilities
2. __BeautifulSoup4__ -> is another library which is extensively used in Web Scrapping
3. __HTML5LIB__ -> is another library that deals with the HTML5 data foramts.

If you would like to explore this area further and get into the nitigritties of the topic, there are various books and references available. Some of them are highlighted below:

- https://www.oreilly.com/library/view/web-scraping-with/9781491985564/
- https://realpython.com/beautiful-soup-web-scraper-python/
- https://towardsdatascience.com/how-to-web-scrape-with-python-in-4-minutes-bc49186a8460


## Reading SQL data from database servers

In real-life applications, most of the time data is stored in the SQL-based relational databases such as MySQL, SQL Server, PostgreSQL, and so on, and various non-SQL databases like NoSQL, MongoDB, and so on. 
 
The database in use is dependent on various architectural factors, and Python provides the mechanisms to read the data from the databases directly. This loading of data from SQL to Pandas is relatively straightforward once the connection to the database is established because both the SQL tables and DataFrame have similar constructs; that is, row labels and column labels.

In Module 6, we go into the details of database designs, data definition, and data manipulation language, as well as SQL operations, to read the databases and perform various analytics activities.
For this section, we will leverage an in-memory SQLite database using Python's built-in SQLite3 server. The focus of this session will be to read the data from the existing tables only.

Run the following code by creating a dummy database and data in it.

In [41]:
##Create Database and Dummy Data
import sqlite3

query="""
CREATE TABLE PERSON(
FirstName VARCHAR(20),
LastName VARCHAR(20),
Age INTEGER,
City VARCHAR(20),
Country VARCHAR(20)
);
"""
con = sqlite3.connect(':memory:')
con.execute(query)
con.commit()

data = [('John', 'Adams', 34, 'New York', 'USA'),
('John', 'Mathews', 34, 'Berlin', 'Germany'),
('John', 'Abraham', 44, 'Paris', 'France'),
('Manoj', 'Sharma', 31, 'Delhi', 'India'),
('Pramod', 'Saini', 34, 'New York', 'USA'),
('Mark', 'Rolton', 42, 'Brisbane', 'Australia')]

stmt = "INSERT into Person VALUES(?,?,?,?,?)"
con.executemany(stmt, data)
con.commit()

### Reading Data from SQL Database

We have created a table named __Person__ in SQLite3, an in-memory database available with Python 3, and we will explore how to access the data from this database table.
 
In general, execute the following steps when you want to connect and access a database from any database via any programming language:

- Create a connection object with the database, also known as a connection string.
- Draft the SQL Query execution on that connection.
- Using the Execute Method provided by that Programming Language, run the query over the connection created.
 
For Python, we have a __read_sql()__ method provided by Pandas in the pandas.io.sql module, and we will leverage that to read the data from the database table Person.
 
See the code snippet below where we perform the above three activities, and read the data from the table named __Person__.

In [42]:
import pandas.io.sql as sql
import sqlite3

#Step1: Create Connetion Object or use Previously created connectiom obect
#con = sqlite3.connect(':memory:')

#Step 2: Create Query to be executed
query = 'SELECT * from PERSON'

#Step 3: Execute the Query using read_sql function, and passing the query 
#and connection objects
df = pd.read_sql(query, con)
df


FirstName LastName  Age      City    Country
0      John    Adams   34  New York        USA
1      John  Mathews   34    Berlin    Germany
2      John  Abraham   44     Paris     France
3     Manoj   Sharma   31     Delhi      India
4    Pramod    Saini   34  New York        USA
5      Mark   Rolton   42  Brisbane  Australia

### Writing DataFrame data to Files

So far, we have used various functions to read the data from files into Pandas DataFrame. There may be scenarios where we may have to write the data back into files. Pandas provide the functions to write the data back into files. In this section, we will look at the following two functions:

- to_csv() -> this method can create a CSV file based on the data in the DataFrame.
- to_json() -> this method can create a JSON file based on the data in the DataFrame.

### Writing a CSV file

The code snippet shows where we will create a CSV file using the function read_csv() function on a DataFrame.
   

In [43]:
#Check the DataFrame
df

FirstName LastName  Age      City    Country
0      John    Adams   34  New York        USA
1      John  Mathews   34    Berlin    Germany
2      John  Abraham   44     Paris     France
3     Manoj   Sharma   31     Delhi      India
4    Pramod    Saini   34  New York        USA
5      Mark   Rolton   42  Brisbane  Australia

In [44]:
#Lets create a csv file with the above data
filename = "dataset/file_csv_1.csv"
df.to_csv(filename)

We can see that the file has been created at the specified location i.e. __"dataset/"__. See the screenshot below:<br>
!["CSV File Created"](file_csv_1.png)
<br> You can also see the data in the file, see the screenshot below:<br>
!["CSV_File_Data"](file_csv_1_data.png)


### Writing a JSON File

See the below code snippet below where we will create a JSON file using the function to_json() on a DataFrame.

In [47]:
filename = "dataset/file_json_1.json"
df.to_json(filename)

We can see that the file has been created at the specified location i.e. __"dataset/"__. See the screenshot below:<br>
!["CSV File Created"](file_json_1.png)
<br> You can also see the data in the file, see the screenshot below:<br>
!["CSV_File_Data"](file_json_1_data.png)


Observe that the default data orientation of  'Column' is used to create the JSON file.

You can control the data orientation in the __to_json()__ function by passing an orient parameter. 

The code snippet shows where we will pass the __orient='split'__ parameter, and you can see the resulting JSON file has a different data orientation now


In [48]:
filename = "dataset/file_json_split.json"
df.to_json(filename, orient='split')

We can see that the file has been created at the specified location i.e. __"dataset/"__. See the screenshot below:<br>
!["CSV File Created"](file_json_split.png)
<br> You can also see the data in the file, see the screenshot below:<br>
!["CSV_File_Data"](file_json_split_data.png)
